### ISSUE TITLE
odroid dropbox sync - permission denied

### ISSUE THREAD

**Issue by OmerShubi** [Addalin/cameranetwork#19]
#TODO Add log

**Comment by OmerShubi** [comment]
Makes sense as it tries connecting to Amit's dropbox

**Comment by Addalin** [comment]
According to [meeting](https://trello.com/c/tlI7Buce) with Amit - this is legacy. 
@scaperex I think we should consider updating to a newer version, that excludes legacy options. This is currently not affecting our work. Therefore, closing this issue.
