### ISSUE TITLE
Installing client_env  fails on windows 10

### ISSUE THREAD

**Issue by Addalin** [Addalin/cameranetwork#24]
Running ` conda env create -f client_venv.yml` fails on a Windows machine. 

> Note: before running I changed the "prefix" name according to anaconda location on the local machine. i.e. "C:\ProgramData\Anaconda2\envs\\<env_name>"

TODO : 

- [x] Check if the "dependencies" are similar/different than in Linux? 

- [x] Create client_env.yml for Windows - if different. 

- [x] Update 'Installation - Client' section in  [install.rst](https://github.com/Addalin/cameranetwork/blob/master/docs/source/install.rst)  accordingly, see https://github.com/Addalin/cameranetwork/commit/9beab0e

**Comment by OmerShubi** [comment]
see [the updated documentation](/docs/source/install.rst#installation---client)
